import { LibraryBranch, LibrarySystem } from '@/types';

export const LIBRARY_SYSTEMS: LibrarySystem[] = [
  {
    id: 'ppl',
    name: 'Pasadena Public Library',
    city: 'Pasadena',
    state: 'CA',
    website: 'https://www.cityofpasadena.net/library/',
    color: '#e11d48', // Rose
    providerType: 'trumba',
  },
  {
    id: 'sppl',
    name: 'South Pasadena Public Library',
    city: 'South Pasadena',
    state: 'CA',
    website: 'https://www.southpasadenaca.gov/government/departments/library',
    color: '#0d9488', // Teal
    providerType: 'libcal',
  },
  {
    id: 'ald',
    name: 'Altadena Library District',
    city: 'Altadena',
    state: 'CA',
    website: 'https://www.altadenalibrary.net',
    color: '#d97706', // Amber
    providerType: 'libcal',
  },
  {
    id: 'glac',
    name: 'Glendale Library, Arts & Culture',
    city: 'Glendale',
    state: 'CA',
    website: 'https://www.glendaleca.gov/government/departments/library-arts-culture',
    color: '#7c3aed', // Purple
    providerType: 'libcal',
  },
  {
    id: 'crowell',
    name: 'Crowell Public Library (San Marino)',
    city: 'San Marino',
    state: 'CA',
    website: 'https://www.crowellpubliclibrary.org',
    color: '#059669', // Emerald
    providerType: 'libcal',
  },
  {
    id: 'alhambra',
    name: 'Alhambra Civic Center Library',
    city: 'Alhambra',
    state: 'CA',
    website: 'https://www.alhambralibrary.org',
    color: '#2563eb', // Blue
    providerType: 'communico',
  },
  {
    id: 'lacounty',
    name: 'LA County Library',
    city: 'Los Angeles',
    state: 'CA',
    website: 'https://lacountylibrary.org',
    color: '#ea580c', // Orange
    providerType: 'libcal',
  },
  {
    id: 'lapl',
    name: 'Los Angeles Public Library',
    city: 'Los Angeles',
    state: 'CA',
    website: 'https://www.lapl.org',
    color: '#0891b2', // Cyan
    providerType: 'libcal',
  },
  {
    id: 'spl',
    name: 'Seattle Public Library',
    city: 'Seattle',
    state: 'WA',
    website: 'https://www.spl.org',
    color: '#0284c7', // Sky Blue
    providerType: 'trumba',
  },
  {
    id: 'kcls',
    name: 'King County Library System',
    city: 'Issaquah',
    state: 'WA',
    website: 'https://kcls.org',
    color: '#059669',
    providerType: 'libcal',
  },
  {
    id: 'nypl',
    name: 'New York Public Library',
    city: 'New York',
    state: 'NY',
    website: 'https://www.nypl.org',
    color: '#dc2626',
    providerType: 'libcal',
  },
  {
    id: 'bpl',
    name: 'Brooklyn Public Library',
    city: 'Brooklyn',
    state: 'NY',
    website: 'https://www.bklynlibrary.org',
    color: '#d97706',
    providerType: 'communico',
  },
  {
    id: 'sfpl',
    name: 'San Francisco Public Library',
    city: 'San Francisco',
    state: 'CA',
    website: 'https://sfpl.org',
    color: '#7c3aed',
    providerType: 'libcal',
  },
  {
    id: 'cpl',
    name: 'Chicago Public Library',
    city: 'Chicago',
    state: 'IL',
    website: 'https://www.chipublib.org',
    color: '#2563eb',
    providerType: 'communico',
  },
  {
    id: 'apl',
    name: 'Austin Public Library',
    city: 'Austin',
    state: 'TX',
    website: 'https://library.austintexas.gov',
    color: '#ea580c',
    providerType: 'libcal',
  },
];

export const LIBRARY_BRANCHES: LibraryBranch[] = [
  // ==========================================
  // PASADENA PUBLIC LIBRARY (PPL)
  // ==========================================
  {
    id: 'ppl-jefferson',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: "Jefferson Branch (Children's & Youth)",
    address: '1500 E Villa St',
    city: 'Pasadena',
    state: 'CA',
    zip: '91106',
    lat: 34.1504,
    lon: -118.1205,
    phone: '(626) 744-8046',
    website: 'https://www.cityofpasadena.net/library/branches/jefferson-branch-library/',
  },
  {
    id: 'ppl-hastings',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'Hastings Branch',
    address: '3325 E Orange Grove Blvd',
    city: 'Pasadena',
    state: 'CA',
    zip: '91107',
    lat: 34.1673,
    lon: -118.0837,
    phone: '(626) 744-7262',
    website: 'https://www.cityofpasadena.net/library/branches/hastings-branch-library/',
  },
  {
    id: 'ppl-allendale',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'Allendale Branch',
    address: '1130 S Marengo Ave',
    city: 'Pasadena',
    state: 'CA',
    zip: '91106',
    lat: 34.1299,
    lon: -118.1507,
    phone: '(626) 744-7260',
    website: 'https://www.cityofpasadena.net/library/branches/allendale-branch-library/',
  },
  {
    id: 'ppl-hill-ave',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'Hill Avenue Branch',
    address: '55 S Hill Ave',
    city: 'Pasadena',
    state: 'CA',
    zip: '91106',
    lat: 34.1456,
    lon: -118.1258,
    phone: '(626) 744-7264',
    website: 'https://www.cityofpasadena.net/library/branches/hill-avenue-branch-library/',
  },
  {
    id: 'ppl-lamanda-park',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'Lamanda Park Branch',
    address: '140 S Altadena Dr',
    city: 'Pasadena',
    state: 'CA',
    zip: '91107',
    lat: 34.1451,
    lon: -118.0934,
    phone: '(626) 744-7266',
    website: 'https://www.cityofpasadena.net/library/branches/lamanda-park-branch-library/',
  },
  {
    id: 'ppl-la-pintoresca',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'La Pintoresca Branch',
    address: '1355 N Raymond Ave',
    city: 'Pasadena',
    state: 'CA',
    zip: '91103',
    lat: 34.1675,
    lon: -118.1498,
    phone: '(626) 744-7268',
    website: 'https://www.cityofpasadena.net/library/branches/la-pintoresca-branch-library/',
  },
  {
    id: 'ppl-santa-catalina',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'Santa Catalina Branch',
    address: '999 E Washington Blvd',
    city: 'Pasadena',
    state: 'CA',
    zip: '91104',
    lat: 34.1624,
    lon: -118.1318,
    phone: '(626) 744-7272',
    website: 'https://www.cityofpasadena.net/library/branches/santa-catalina-branch-library/',
  },
  {
    id: 'ppl-san-rafael',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'San Rafael Branch',
    address: '1240 Nithsdale Rd',
    city: 'Pasadena',
    state: 'CA',
    zip: '91105',
    lat: 34.1408,
    lon: -118.1793,
    phone: '(626) 744-7270',
    website: 'https://www.cityofpasadena.net/library/branches/san-rafael-branch-library/',
  },
  {
    id: 'ppl-linda-vista',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'Linda Vista Branch',
    address: '1281 Bryant St',
    city: 'Pasadena',
    state: 'CA',
    zip: '91103',
    lat: 34.1601,
    lon: -118.1742,
    phone: '(626) 744-7278',
    website: 'https://www.cityofpasadena.net/library/branches/linda-vista-branch-library/',
  },

  // ==========================================
  // SOUTH PASADENA PUBLIC LIBRARY
  // ==========================================
  {
    id: 'sppl-main',
    systemId: 'sppl',
    systemName: 'South Pasadena Public Library',
    name: 'South Pasadena Public Library',
    address: '1100 Oxley St',
    city: 'South Pasadena',
    state: 'CA',
    zip: '91030',
    lat: 34.1166,
    lon: -118.1528,
    phone: '(626) 403-7330',
    website: 'https://www.southpasadenaca.gov/government/departments/library',
  },

  // ==========================================
  // ALTADENA LIBRARY DISTRICT (ALD)
  // ==========================================
  {
    id: 'ald-main',
    systemId: 'ald',
    systemName: 'Altadena Library District',
    name: 'Altadena Main Library',
    address: '600 E Mariposa St',
    city: 'Altadena',
    state: 'CA',
    zip: '91001',
    lat: 34.1925,
    lon: -118.1388,
    phone: '(626) 798-0833',
    website: 'https://www.altadenalibrary.net',
  },
  {
    id: 'ald-bob-lucas',
    systemId: 'ald',
    systemName: 'Altadena Library District',
    name: 'Bob Lucas Memorial Branch',
    address: '2659 Lincoln Ave',
    city: 'Altadena',
    state: 'CA',
    zip: '91001',
    lat: 34.1843,
    lon: -118.1593,
    phone: '(626) 798-8338',
    website: 'https://www.altadenalibrary.net/locations/bob-lucas/',
  },

  // ==========================================
  // CROWELL PUBLIC LIBRARY (SAN MARINO)
  // ==========================================
  {
    id: 'crowell-main',
    systemId: 'crowell',
    systemName: 'Crowell Public Library',
    name: 'Crowell Public Library',
    address: '1890 Huntington Dr',
    city: 'San Marino',
    state: 'CA',
    zip: '91108',
    lat: 34.1221,
    lon: -118.1189,
    phone: '(626) 300-0777',
    website: 'https://www.crowellpubliclibrary.org',
  },

  // ==========================================
  // ALHAMBRA CIVIC CENTER LIBRARY
  // ==========================================
  {
    id: 'alhambra-main',
    systemId: 'alhambra',
    systemName: 'Alhambra Civic Center Library',
    name: 'Alhambra Civic Center Library',
    address: '100 W Main St',
    city: 'Alhambra',
    state: 'CA',
    zip: '91801',
    lat: 34.0955,
    lon: -118.1287,
    phone: '(626) 570-5008',
    website: 'https://www.alhambralibrary.org',
  },

  // ==========================================
  // GLENDALE LIBRARY, ARTS & CULTURE
  // ==========================================
  {
    id: 'glac-central',
    systemId: 'glac',
    systemName: 'Glendale Library, Arts & Culture',
    name: 'Glendale Central Library',
    address: '222 E Harvard St',
    city: 'Glendale',
    state: 'CA',
    zip: '91205',
    lat: 34.1438,
    lon: -118.2525,
    phone: '(818) 548-2021',
    website: 'https://www.glendaleca.gov/government/departments/library-arts-culture/central-library',
  },
  {
    id: 'glac-brand',
    systemId: 'glac',
    systemName: 'Glendale Library, Arts & Culture',
    name: 'Brand Library & Art Center',
    address: '1601 W Mountain St',
    city: 'Glendale',
    state: 'CA',
    zip: '91201',
    lat: 34.1818,
    lon: -118.2713,
    phone: '(818) 548-2051',
    website: 'https://www.glendaleca.gov/government/departments/library-arts-culture/brand-library-art-center',
  },
  {
    id: 'glac-adams-square',
    systemId: 'glac',
    systemName: 'Glendale Library, Arts & Culture',
    name: 'Adams Square Branch Library',
    address: '1100 E Chevy Chase Dr',
    city: 'Glendale',
    state: 'CA',
    zip: '91205',
    lat: 34.1378,
    lon: -118.2372,
    phone: '(818) 548-3830',
    website: 'https://www.glendaleca.gov/government/departments/library-arts-culture',
  },
  {
    id: 'glac-montrose',
    systemId: 'glac',
    systemName: 'Glendale Library, Arts & Culture',
    name: 'Montrose Branch Library',
    address: '2465 Honolulu Ave',
    city: 'Montrose',
    state: 'CA',
    zip: '91020',
    lat: 34.2081,
    lon: -118.2307,
    phone: '(818) 548-2048',
    website: 'https://www.glendaleca.gov/government/departments/library-arts-culture',
  },

  // ==========================================
  // LA COUNTY LIBRARY (SAN GABRIEL VALLEY / FOOTHILL)
  // ==========================================
  {
    id: 'lacounty-san-gabriel',
    systemId: 'lacounty',
    systemName: 'LA County Library',
    name: 'San Gabriel Library',
    address: '500 S Del Mar Ave',
    city: 'San Gabriel',
    state: 'CA',
    zip: '91776',
    lat: 34.0945,
    lon: -118.1005,
    phone: '(626) 287-0761',
    website: 'https://lacountylibrary.org/san-gabriel-library/',
  },
  {
    id: 'lacounty-temple-city',
    systemId: 'lacounty',
    systemName: 'LA County Library',
    name: 'Temple City Library',
    address: '5939 Golden West Ave',
    city: 'Temple City',
    state: 'CA',
    zip: '91780',
    lat: 34.1085,
    lon: -118.0583,
    phone: '(626) 285-2136',
    website: 'https://lacountylibrary.org/temple-city-library/',
  },
  {
    id: 'lacounty-rosemead',
    systemId: 'lacounty',
    systemName: 'LA County Library',
    name: 'Rosemead Library',
    address: '8800 Valley Blvd',
    city: 'Rosemead',
    state: 'CA',
    zip: '91770',
    lat: 34.0709,
    lon: -118.0833,
    phone: '(626) 572-2320',
    website: 'https://lacountylibrary.org/rosemead-library/',
  },
  {
    id: 'lacounty-la-canada',
    systemId: 'lacounty',
    systemName: 'LA County Library',
    name: 'La Cañada Flintridge Library',
    address: '4545 N Oakwood Ave',
    city: 'La Cañada Flintridge',
    state: 'CA',
    zip: '91011',
    lat: 34.2045,
    lon: -118.2014,
    phone: '(818) 790-0522',
    website: 'https://lacountylibrary.org/la-canada-flintridge-library/',
  },

  // ==========================================
  // LOS ANGELES PUBLIC LIBRARY (LAPL) - Close to Pasadena + Central
  // ==========================================
  {
    id: 'lapl-eagle-rock',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Eagle Rock Branch',
    address: '2225 Colorado Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90041',
    lat: 34.1396,
    lon: -118.2114,
    phone: '(323) 258-8078',
    website: 'https://www.lapl.org/branches/eagle-rock',
  },
  {
    id: 'lapl-arroyo-seco',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Arroyo Seco Regional Branch',
    address: '6145 N Figueroa St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90042',
    lat: 34.1105,
    lon: -118.1923,
    phone: '(323) 256-3141',
    website: 'https://www.lapl.org/branches/arroyo-seco',
  },
  {
    id: 'lapl-chinatown',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Chinatown Branch',
    address: '639 N Hill St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90012',
    lat: 34.0622,
    lon: -118.2385,
    phone: '(213) 620-0925',
    website: 'https://www.lapl.org/branches/chinatown',
  },
  {
    id: 'lapl-lincoln-heights',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Lincoln Heights Branch',
    address: '2530 Workman St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90031',
    lat: 34.0735,
    lon: -118.2155,
    phone: '(323) 225-9201',
    website: 'https://www.lapl.org/branches/lincoln-heights',
  },
  {
    id: 'lapl-central',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Central Library',
    address: '630 W 5th St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90071',
    lat: 34.0503,
    lon: -118.2553,
    phone: '(213) 228-7000',
    website: 'https://www.lapl.org/branches/central-library',
  },
  {
    id: 'lapl-venice',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Venice - Abbot Kinney Memorial Branch',
    address: '501 S Venice Blvd',
    city: 'Venice',
    state: 'CA',
    zip: '90291',
    lat: 33.9877,
    lon: -118.4632,
    phone: '(310) 821-1769',
    website: 'https://www.lapl.org/branches/venice',
  },

  // ==========================================
  // SEATTLE PUBLIC LIBRARY (SPL) - ALL 27 LOCATIONS
  // ==========================================
  {
    id: 'spl-central',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Central Library',
    address: '1000 4th Ave',
    city: 'Seattle',
    state: 'WA',
    zip: '98104',
    lat: 47.6067,
    lon: -122.3326,
    phone: '(206) 386-4636',
    website: 'https://www.spl.org/hours-and-locations/central-library',
  },
  {
    id: 'spl-ballard',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Ballard Branch',
    address: '5614 22nd Ave NW',
    city: 'Seattle',
    state: 'WA',
    zip: '98107',
    lat: 47.6698,
    lon: -122.3853,
    phone: '(206) 684-4089',
    website: 'https://www.spl.org/hours-and-locations/ballard-branch',
  },
  {
    id: 'spl-beacon-hill',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Beacon Hill Branch',
    address: '2821 Beacon Ave S',
    city: 'Seattle',
    state: 'WA',
    zip: '98144',
    lat: 47.5779,
    lon: -122.3129,
    phone: '(206) 684-4011',
    website: 'https://www.spl.org/hours-and-locations/beacon-hill-branch',
  },
  {
    id: 'spl-broadview',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Broadview Branch',
    address: '12755 Greenwood Ave N',
    city: 'Seattle',
    state: 'WA',
    zip: '98133',
    lat: 47.7222,
    lon: -122.3557,
    phone: '(206) 684-7519',
    website: 'https://www.spl.org/hours-and-locations/broadview-branch',
  },
  {
    id: 'spl-capitol-hill',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Capitol Hill Branch',
    address: '425 Harvard Ave E',
    city: 'Seattle',
    state: 'WA',
    zip: '98102',
    lat: 47.6228,
    lon: -122.3228,
    phone: '(206) 684-4715',
    website: 'https://www.spl.org/hours-and-locations/capitol-hill-branch',
  },
  {
    id: 'spl-columbia',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Columbia Branch',
    address: '4721 Rainier Ave S',
    city: 'Seattle',
    state: 'WA',
    zip: '98118',
    lat: 47.5601,
    lon: -122.2858,
    phone: '(206) 386-1908',
    website: 'https://www.spl.org/hours-and-locations/columbia-branch',
  },
  {
    id: 'spl-delridge',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Delridge Branch',
    address: '5423 Delridge Way SW',
    city: 'Seattle',
    state: 'WA',
    zip: '98106',
    lat: 47.5532,
    lon: -122.3630,
    phone: '(206) 733-9125',
    website: 'https://www.spl.org/hours-and-locations/delridge-branch',
  },
  {
    id: 'spl-douglass-truth',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Douglass-Truth Branch',
    address: '2300 E Yesler Way',
    city: 'Seattle',
    state: 'WA',
    zip: '98122',
    lat: 47.6015,
    lon: -122.3023,
    phone: '(206) 684-4704',
    website: 'https://www.spl.org/hours-and-locations/douglass-truth-branch',
  },
  {
    id: 'spl-fremont',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Fremont Branch',
    address: '731 N 35th St',
    city: 'Seattle',
    state: 'WA',
    zip: '98103',
    lat: 47.6511,
    lon: -122.3486,
    phone: '(206) 684-4084',
    website: 'https://www.spl.org/hours-and-locations/fremont-branch',
  },
  {
    id: 'spl-green-lake',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Green Lake Branch',
    address: '7364 E Green Lake Dr N',
    city: 'Seattle',
    state: 'WA',
    zip: '98115',
    lat: 47.6826,
    lon: -122.3283,
    phone: '(206) 684-7547',
    website: 'https://www.spl.org/hours-and-locations/green-lake-branch',
  },
  {
    id: 'spl-greenwood',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Greenwood Branch',
    address: '8016 Greenwood Ave N',
    city: 'Seattle',
    state: 'WA',
    zip: '98103',
    lat: 47.6876,
    lon: -122.3553,
    phone: '(206) 684-4086',
    website: 'https://www.spl.org/hours-and-locations/greenwood-branch',
  },
  {
    id: 'spl-high-point',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'High Point Branch',
    address: '3411 SW Raymond St',
    city: 'Seattle',
    state: 'WA',
    zip: '98126',
    lat: 47.5451,
    lon: -122.3758,
    phone: '(206) 684-7454',
    website: 'https://www.spl.org/hours-and-locations/high-point-branch',
  },
  {
    id: 'spl-id-chinatown',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'International District/Chinatown Branch',
    address: '713 8th Ave S',
    city: 'Seattle',
    state: 'WA',
    zip: '98104',
    lat: 47.5976,
    lon: -122.3228,
    phone: '(206) 386-1888',
    website: 'https://www.spl.org/hours-and-locations/international-district-chinatown-branch',
  },
  {
    id: 'spl-lake-city',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Lake City Branch',
    address: '12501 28th Ave NE',
    city: 'Seattle',
    state: 'WA',
    zip: '98125',
    lat: 47.7198,
    lon: -122.2982,
    phone: '(206) 684-7518',
    website: 'https://www.spl.org/hours-and-locations/lake-city-branch',
  },
  {
    id: 'spl-madrona',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Madrona-Sally Goldmark Branch',
    address: '1134 33rd Ave',
    city: 'Seattle',
    state: 'WA',
    zip: '98122',
    lat: 47.6127,
    lon: -122.2898,
    phone: '(206) 684-4039',
    website: 'https://www.spl.org/hours-and-locations/madrona-sally-goldmark-branch',
  },
  {
    id: 'spl-magnolia',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Magnolia Branch',
    address: '2801 34th Ave W',
    city: 'Seattle',
    state: 'WA',
    zip: '98199',
    lat: 47.6441,
    lon: -122.3995,
    phone: '(206) 386-4225',
    website: 'https://www.spl.org/hours-and-locations/magnolia-branch',
  },
  {
    id: 'spl-montlake',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Montlake Branch',
    address: '2401 24th Ave E',
    city: 'Seattle',
    state: 'WA',
    zip: '98112',
    lat: 47.6409,
    lon: -122.3023,
    phone: '(206) 684-4720',
    website: 'https://www.spl.org/hours-and-locations/montlake-branch',
  },
  {
    id: 'spl-newholly',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'NewHolly Branch',
    address: '7058 32nd Ave S',
    city: 'Seattle',
    state: 'WA',
    zip: '98118',
    lat: 47.5387,
    lon: -122.2925,
    phone: '(206) 386-1905',
    website: 'https://www.spl.org/hours-and-locations/newholly-branch',
  },
  {
    id: 'spl-northeast',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Northeast Branch',
    address: '6801 35th Ave NE',
    city: 'Seattle',
    state: 'WA',
    zip: '98115',
    lat: 47.6781,
    lon: -122.2903,
    phone: '(206) 684-7539',
    website: 'https://www.spl.org/hours-and-locations/northeast-branch',
  },
  {
    id: 'spl-northgate',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Northgate Branch',
    address: '10548 5th Ave NE',
    city: 'Seattle',
    state: 'WA',
    zip: '98125',
    lat: 47.7056,
    lon: -122.3235,
    phone: '(206) 386-1980',
    website: 'https://www.spl.org/hours-and-locations/northgate-branch',
  },
  {
    id: 'spl-queen-anne',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Queen Anne Branch',
    address: '400 W Garfield St',
    city: 'Seattle',
    state: 'WA',
    zip: '98119',
    lat: 47.6322,
    lon: -122.3619,
    phone: '(206) 386-4227',
    website: 'https://www.spl.org/hours-and-locations/queen-anne-branch',
  },
  {
    id: 'spl-rainier-beach',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Rainier Beach Branch',
    address: '9125 Rainier Ave S',
    city: 'Seattle',
    state: 'WA',
    zip: '98118',
    lat: 47.5218,
    lon: -122.2709,
    phone: '(206) 386-1906',
    website: 'https://www.spl.org/hours-and-locations/rainier-beach-branch',
  },
  {
    id: 'spl-south-park',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'South Park Branch',
    address: '8604 8th Ave S',
    city: 'Seattle',
    state: 'WA',
    zip: '98108',
    lat: 47.5262,
    lon: -122.3232,
    phone: '(206) 615-1688',
    website: 'https://www.spl.org/hours-and-locations/south-park-branch',
  },
  {
    id: 'spl-southwest',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Southwest Branch',
    address: '9010 35th Ave SW',
    city: 'Seattle',
    state: 'WA',
    zip: '98126',
    lat: 47.5222,
    lon: -122.3768,
    phone: '(206) 684-7455',
    website: 'https://www.spl.org/hours-and-locations/southwest-branch',
  },
  {
    id: 'spl-university',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'University Branch',
    address: '5009 Roosevelt Way NE',
    city: 'Seattle',
    state: 'WA',
    zip: '98105',
    lat: 47.6653,
    lon: -122.3175,
    phone: '(206) 684-4063',
    website: 'https://www.spl.org/hours-and-locations/university-branch',
  },
  {
    id: 'spl-wallingford',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Wallingford Branch',
    address: '1501 N 45th St',
    city: 'Seattle',
    state: 'WA',
    zip: '98103',
    lat: 47.6610,
    lon: -122.3392,
    phone: '(206) 684-4088',
    website: 'https://www.spl.org/hours-and-locations/wallingford-branch',
  },
  {
    id: 'spl-west-seattle',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'West Seattle Branch',
    address: '2306 42nd Ave SW',
    city: 'Seattle',
    state: 'WA',
    zip: '98116',
    lat: 47.5828,
    lon: -122.3855,
    phone: '(206) 684-7444',
    website: 'https://www.spl.org/hours-and-locations/west-seattle-branch',
  },

  // ==========================================
  // KING COUNTY LIBRARY SYSTEM (KCLS)
  // ==========================================
  {
    id: 'kcls-bellevue',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Bellevue Library',
    address: '1111 110th Ave NE',
    city: 'Bellevue',
    state: 'WA',
    zip: '98004',
    lat: 47.6203,
    lon: -122.1932,
    phone: '(425) 450-1765',
    website: 'https://kcls.org/locations/1490',
  },
  {
    id: 'kcls-kirkland',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Kirkland Library',
    address: '308 Kirkland Ave',
    city: 'Kirkland',
    state: 'WA',
    zip: '98033',
    lat: 47.6766,
    lon: -122.2036,
    phone: '(425) 822-2459',
    website: 'https://kcls.org/locations/1517',
  },
  {
    id: 'kcls-redmond',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Redmond Library',
    address: '15990 NE 85th St',
    city: 'Redmond',
    state: 'WA',
    zip: '98052',
    lat: 47.6791,
    lon: -122.1264,
    phone: '(425) 885-1861',
    website: 'https://kcls.org/locations/1531',
  },
  {
    id: 'kcls-mercer-island',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Mercer Island Library',
    address: '4400 88th Ave SE',
    city: 'Mercer Island',
    state: 'WA',
    zip: '98040',
    lat: 47.5684,
    lon: -122.2215,
    phone: '(206) 236-3537',
    website: 'https://kcls.org/locations/1523',
  },
  {
    id: 'kcls-shoreline',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Shoreline Library',
    address: '345 NE 175th St',
    city: 'Shoreline',
    state: 'WA',
    zip: '98155',
    lat: 47.7565,
    lon: -122.3255,
    phone: '(206) 362-7550',
    website: 'https://kcls.org/locations/1538',
  },
  {
    id: 'kcls-lake-forest-park',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Lake Forest Park Library',
    address: '17171 Bothell Way NE',
    city: 'Lake Forest Park',
    state: 'WA',
    zip: '98155',
    lat: 47.7533,
    lon: -122.2778,
    phone: '(206) 362-8860',
    website: 'https://kcls.org/locations/1519',
  },
  {
    id: 'kcls-bothell',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Bothell Library',
    address: '18215 98th Ave NE',
    city: 'Bothell',
    state: 'WA',
    zip: '98011',
    lat: 47.7601,
    lon: -122.2084,
    phone: '(425) 486-7811',
    website: 'https://kcls.org/locations/1494',
  },
  {
    id: 'kcls-renton',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Renton Library',
    address: '100 Mill Ave S',
    city: 'Renton',
    state: 'WA',
    zip: '98057',
    lat: 47.4805,
    lon: -122.2065,
    phone: '(425) 226-6043',
    website: 'https://kcls.org/locations/1532',
  },
  {
    id: 'kcls-burien',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Burien Library',
    address: '400 SW 152nd St',
    city: 'Burien',
    state: 'WA',
    zip: '98166',
    lat: 47.4659,
    lon: -122.3397,
    phone: '(206) 243-3490',
    website: 'https://kcls.org/locations/1497',
  },
  {
    id: 'kcls-white-center',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'White Center Library',
    address: '1409 SW 107th St',
    city: 'Seattle',
    state: 'WA',
    zip: '98146',
    lat: 47.5065,
    lon: -122.3524,
    phone: '(206) 243-0233',
    website: 'https://kcls.org/locations/1545',
  },
  {
    id: 'kcls-tukwila',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Tukwila Library',
    address: '14380 Tukwila International Blvd',
    city: 'Tukwila',
    state: 'WA',
    zip: '98168',
    lat: 47.4735,
    lon: -122.2858,
    phone: '(206) 242-1640',
    website: 'https://kcls.org/locations/1542',
  },

  // ==========================================
  // NEW YORK PUBLIC LIBRARY & BROOKLYN
  // ==========================================
  {
    id: 'nypl-schwarzman',
    systemId: 'nypl',
    systemName: 'New York Public Library',
    name: 'Stephen A. Schwarzman Building',
    address: '476 5th Ave',
    city: 'New York',
    state: 'NY',
    zip: '10018',
    lat: 40.7532,
    lon: -73.9822,
    phone: '(917) 275-6975',
    website: 'https://www.nypl.org/locations/schwarzman',
  },
  {
    id: 'nypl-snfl',
    systemId: 'nypl',
    systemName: 'New York Public Library',
    name: 'Stavros Niarchos Foundation Library (SNFL)',
    address: '455 5th Ave',
    city: 'New York',
    state: 'NY',
    zip: '10016',
    lat: 40.7518,
    lon: -73.9818,
    phone: '(212) 340-0863',
    website: 'https://www.nypl.org/locations/snfl',
  },
  {
    id: 'bpl-central',
    systemId: 'bpl',
    systemName: 'Brooklyn Public Library',
    name: 'Central Library',
    address: '10 Grand Army Plaza',
    city: 'Brooklyn',
    state: 'NY',
    zip: '11238',
    lat: 40.6725,
    lon: -73.9682,
    phone: '(718) 230-2100',
    website: 'https://www.bklynlibrary.org/locations/central',
  },
  {
    id: 'bpl-park-slope',
    systemId: 'bpl',
    systemName: 'Brooklyn Public Library',
    name: 'Park Slope Library',
    address: '431 6th Ave',
    city: 'Brooklyn',
    state: 'NY',
    zip: '11215',
    lat: 40.6695,
    lon: -73.9841,
    phone: '(718) 832-1853',
    website: 'https://www.bklynlibrary.org/locations/park-slope',
  },

  // ==========================================
  // SAN FRANCISCO PUBLIC LIBRARY (SFPL)
  // ==========================================
  {
    id: 'sfpl-main',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Main Library (Civic Center)',
    address: '100 Larkin St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94102',
    lat: 37.7788,
    lon: -122.4168,
    phone: '(415) 557-4400',
    website: 'https://sfpl.org/locations/main-library',
  },
  {
    id: 'sfpl-mission',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Mission Branch',
    address: '300 Bartlett St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94110',
    lat: 37.7525,
    lon: -122.4198,
    phone: '(415) 355-2800',
    website: 'https://sfpl.org/locations/mission',
  },
  {
    id: 'sfpl-richmond',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Richmond Branch',
    address: '351 9th Ave',
    city: 'San Francisco',
    state: 'CA',
    zip: '94118',
    lat: 37.7815,
    lon: -122.4678,
    phone: '(415) 355-5600',
    website: 'https://sfpl.org/locations/richmond',
  },
  {
    id: 'sfpl-sunset',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Sunset Branch',
    address: '1370 18th Ave',
    city: 'San Francisco',
    state: 'CA',
    zip: '94122',
    lat: 37.7618,
    lon: -122.4764,
    phone: '(415) 355-2818',
    website: 'https://sfpl.org/locations/sunset',
  },
  {
    id: 'sfpl-marina',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Marina Branch',
    address: '1890 Chestnut St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94123',
    lat: 37.8005,
    lon: -122.4352,
    phone: '(415) 355-2823',
    website: 'https://sfpl.org/locations/marina',
  },
  {
    id: 'sfpl-north-beach',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'North Beach Branch',
    address: '850 Columbus Ave',
    city: 'San Francisco',
    state: 'CA',
    zip: '94133',
    lat: 37.8016,
    lon: -122.4132,
    phone: '(415) 355-5626',
    website: 'https://sfpl.org/locations/north-beach',
  },
  {
    id: 'sfpl-chinatown',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Chinatown / Him Mark Lai Branch',
    address: '1135 Powell St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94108',
    lat: 37.7947,
    lon: -122.4093,
    phone: '(415) 355-2888',
    website: 'https://sfpl.org/locations/chinatown',
  },
  {
    id: 'sfpl-noe-valley',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Noe Valley / Sally Brunn Branch',
    address: '451 Jersey St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94114',
    lat: 37.7513,
    lon: -122.4347,
    phone: '(415) 355-5707',
    website: 'https://sfpl.org/locations/noe-valley',
  },
  {
    id: 'sfpl-bernal-heights',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Bernal Heights Branch',
    address: '500 Cortland Ave',
    city: 'San Francisco',
    state: 'CA',
    zip: '94110',
    lat: 37.7391,
    lon: -122.4158,
    phone: '(415) 355-2810',
    website: 'https://sfpl.org/locations/bernal-heights',
  },
  {
    id: 'sfpl-glen-park',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Glen Park Branch',
    address: '2825 Diamond St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94131',
    lat: 37.7335,
    lon: -122.4338,
    phone: '(415) 355-2858',
    website: 'https://sfpl.org/locations/glen-park',
  },
  {
    id: 'sfpl-eureka-valley',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Eureka Valley / Harvey Milk Memorial Branch',
    address: '1 José Sarria Ct',
    city: 'San Francisco',
    state: 'CA',
    zip: '94114',
    lat: 37.7612,
    lon: -122.4348,
    phone: '(415) 355-5616',
    website: 'https://sfpl.org/locations/eureka-valley',
  },
  {
    id: 'sfpl-west-portal',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'West Portal Branch',
    address: '190 Lenox Way',
    city: 'San Francisco',
    state: 'CA',
    zip: '94127',
    lat: 37.7402,
    lon: -122.4665,
    phone: '(415) 355-2886',
    website: 'https://sfpl.org/locations/west-portal',
  },
  {
    id: 'sfpl-parkside',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Parkside Branch',
    address: '1200 Taraval St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94116',
    lat: 37.7431,
    lon: -122.4789,
    phone: '(415) 355-5770',
    website: 'https://sfpl.org/locations/parkside',
  },
  {
    id: 'sfpl-western-addition',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Western Addition Branch',
    address: '1550 Scott St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94115',
    lat: 37.7842,
    lon: -122.4382,
    phone: '(415) 355-5727',
    website: 'https://sfpl.org/locations/western-addition',
  },
  {
    id: 'sfpl-presidio',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Presidio Branch',
    address: '3150 Sacramento St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94115',
    lat: 37.7885,
    lon: -122.4452,
    phone: '(415) 355-5660',
    website: 'https://sfpl.org/locations/presidio',
  },
  {
    id: 'sfpl-potrero',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Potrero Branch',
    address: '1616 20th St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94107',
    lat: 37.7618,
    lon: -122.3985,
    phone: '(415) 355-2822',
    website: 'https://sfpl.org/locations/potrero',
  },
  {
    id: 'sfpl-mission-bay',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Mission Bay Branch',
    address: '960 4th St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94158',
    lat: 37.7735,
    lon: -122.3932,
    phone: '(415) 355-2838',
    website: 'https://sfpl.org/locations/mission-bay',
  },
  {
    id: 'sfpl-bayview',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Bayview / Linda Brooks-Burton Branch',
    address: '5075 3rd St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94124',
    lat: 37.7303,
    lon: -122.3892,
    phone: '(415) 355-5757',
    website: 'https://sfpl.org/locations/bayview',
  },
  {
    id: 'sfpl-park',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Park Branch (Haight-Ashbury)',
    address: '1833 Page St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94117',
    lat: 37.7705,
    lon: -122.4498,
    phone: '(415) 355-5656',
    website: 'https://sfpl.org/locations/park',
  },

  // ==========================================
  // CHICAGO & AUSTIN
  // ==========================================
  {
    id: 'cpl-lincoln-park',
    systemId: 'cpl',
    systemName: 'Chicago Public Library',
    name: 'Lincoln Park Branch',
    address: '1150 W Fullerton Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60614',
    lat: 41.9252,
    lon: -87.6582,
    phone: '(312) 744-1926',
    website: 'https://www.chipublib.org/locations/44/',
  },
  {
    id: 'apl-central',
    systemId: 'apl',
    systemName: 'Austin Public Library',
    name: 'Central Library',
    address: '710 W Cesar Chavez St',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    lat: 30.2662,
    lon: -97.7495,
    phone: '(512) 974-7400',
    website: 'https://library.austintexas.gov/central-library',
  },
];

// ==========================================
// ADDITIONAL NATIONWIDE REGIONAL BRANCHES
// ==========================================

export const NATIONWIDE_SYSTEMS: LibrarySystem[] = [
  {
    id: 'ppl-tx',
    name: 'Pasadena Public Library (Texas)',
    city: 'Pasadena',
    state: 'TX',
    website: 'https://www.pasadenatx.gov/175/Library',
    color: '#0284c7',
    providerType: 'libcal',
  },
  {
    id: 'hcpl',
    name: 'Harris County Public Library',
    city: 'Houston',
    state: 'TX',
    website: 'https://www.hcpl.net',
    color: '#059669',
    providerType: 'libcal',
  },
  {
    id: 'hpl',
    name: 'Houston Public Library',
    city: 'Houston',
    state: 'TX',
    website: 'https://houstonlibrary.org',
    color: '#7c3aed',
    providerType: 'libcal',
  },
  {
    id: 'dpl',
    name: 'Denver Public Library',
    city: 'Denver',
    state: 'CO',
    website: 'https://www.denverlibrary.org',
    color: '#0891b2',
    providerType: 'libcal',
  },
  {
    id: 'mcl',
    name: 'Multnomah County Library (Portland)',
    city: 'Portland',
    state: 'OR',
    website: 'https://multcolib.org',
    color: '#0d9488',
    providerType: 'libcal',
  },
  {
    id: 'afpls',
    name: 'Atlanta-Fulton Public Library System',
    city: 'Atlanta',
    state: 'GA',
    website: 'https://www.fulcolibrary.org',
    color: '#dc2626',
    providerType: 'libcal',
  },
  {
    id: 'mdpls',
    name: 'Miami-Dade Public Library System',
    city: 'Miami',
    state: 'FL',
    website: 'https://mdpls.org',
    color: '#ea580c',
    providerType: 'libcal',
  },
];

export const NATIONWIDE_BRANCHES: LibraryBranch[] = [
  // --- Pasadena, Texas & Harris County ---
  {
    id: 'ppl-tx-central',
    systemId: 'ppl-tx',
    systemName: 'Pasadena Public Library (Texas)',
    name: 'Central Library',
    address: '1204 Fairmont Pkwy',
    city: 'Pasadena',
    state: 'TX',
    zip: '77504',
    lat: 29.6586,
    lon: -95.1916,
    phone: '(713) 477-0276',
    website: 'https://www.pasadenatx.gov/175/Library',
  },
  {
    id: 'ppl-tx-fairmont',
    systemId: 'ppl-tx',
    systemName: 'Pasadena Public Library (Texas)',
    name: 'Fairmont Branch Library',
    address: '4330 Fairmont Pkwy',
    city: 'Pasadena',
    state: 'TX',
    zip: '77504',
    lat: 29.6575,
    lon: -95.1672,
    phone: '(281) 998-1095',
    website: 'https://www.pasadenatx.gov/175/Library',
  },
  {
    id: 'hcpl-south-houston',
    systemId: 'hcpl',
    systemName: 'Harris County Public Library',
    name: 'South Houston Branch',
    address: '607 Avenue A',
    city: 'South Houston',
    state: 'TX',
    zip: '77587',
    lat: 29.6601,
    lon: -95.2345,
    phone: '(832) 927-5530',
    website: 'https://www.hcpl.net/branch/south-houston-branch-library',
  },
  {
    id: 'hcpl-la-porte',
    systemId: 'hcpl',
    systemName: 'Harris County Public Library',
    name: 'La Porte Branch Library',
    address: '600 S Broadway St',
    city: 'La Porte',
    state: 'TX',
    zip: '77571',
    lat: 29.6631,
    lon: -95.0195,
    phone: '(281) 471-4022',
    website: 'https://www.hcpl.net/branch/la-porte-branch-library',
  },
  {
    id: 'hpl-park-place',
    systemId: 'hpl',
    systemName: 'Houston Public Library',
    name: 'Park Place Regional Library',
    address: '8145 Park Place Blvd',
    city: 'Houston',
    state: 'TX',
    zip: '77017',
    lat: 29.6845,
    lon: -95.2755,
    phone: '(832) 393-1970',
    website: 'https://houstonlibrary.org/location/park-place-regional-library',
  },

  // --- Chicago Public Library (Extended) ---
  {
    id: 'cpl-harold',
    systemId: 'cpl',
    systemName: 'Chicago Public Library',
    name: 'Harold Washington Library Center (Loop)',
    address: '400 S State St',
    city: 'Chicago',
    state: 'IL',
    zip: '60605',
    lat: 41.8763,
    lon: -87.6281,
    phone: '(312) 747-4300',
    website: 'https://www.chipublib.org/locations/34/',
  },
  {
    id: 'cpl-logan-square',
    systemId: 'cpl',
    systemName: 'Chicago Public Library',
    name: 'Logan Square Branch',
    address: '3030 W Fullerton Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60647',
    lat: 41.9248,
    lon: -87.7032,
    phone: '(312) 744-5295',
    website: 'https://www.chipublib.org/locations/45/',
  },
  {
    id: 'cpl-sulzer',
    systemId: 'cpl',
    systemName: 'Chicago Public Library',
    name: 'Sulzer Regional Library (Lincoln Square)',
    address: '4455 N Lincoln Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60625',
    lat: 41.9625,
    lon: -87.6853,
    phone: '(312) 744-7616',
    website: 'https://www.chipublib.org/locations/69/',
  },
  {
    id: 'cpl-chinatown',
    systemId: 'cpl',
    systemName: 'Chicago Public Library',
    name: 'Chinatown Branch',
    address: '2100 S Wentworth Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60616',
    lat: 41.8542,
    lon: -87.6321,
    phone: '(312) 747-8013',
    website: 'https://www.chipublib.org/locations/18/',
  },

  // --- Austin Public Library (Extended) ---
  {
    id: 'apl-twin-oaks',
    systemId: 'apl',
    systemName: 'Austin Public Library',
    name: 'Twin Oaks Branch',
    address: '1800 S 5th St',
    city: 'Austin',
    state: 'TX',
    zip: '78704',
    lat: 30.2458,
    lon: -97.7592,
    phone: '(512) 974-9980',
    website: 'https://library.austintexas.gov/twin-oaks-branch',
  },
  {
    id: 'apl-terrazas',
    systemId: 'apl',
    systemName: 'Austin Public Library',
    name: 'Terrazas Branch (East Austin)',
    address: '1105 E Cesar Chavez St',
    city: 'Austin',
    state: 'TX',
    zip: '78702',
    lat: 30.2588,
    lon: -97.7335,
    phone: '(512) 974-3625',
    website: 'https://library.austintexas.gov/terrazas-branch',
  },
  {
    id: 'apl-milwood',
    systemId: 'apl',
    systemName: 'Austin Public Library',
    name: 'Milwood Branch (North Austin)',
    address: '12500 Amherst Dr',
    city: 'Austin',
    state: 'TX',
    zip: '78727',
    lat: 30.4225,
    lon: -97.7125,
    phone: '(512) 974-9880',
    website: 'https://library.austintexas.gov/milwood-branch',
  },

  // --- Denver Public Library ---
  {
    id: 'dpl-central',
    systemId: 'dpl',
    systemName: 'Denver Public Library',
    name: 'Central Library (Civic Center)',
    address: '10 W 14th Ave Pkwy',
    city: 'Denver',
    state: 'CO',
    zip: '80204',
    lat: 39.7368,
    lon: -104.9882,
    phone: '(720) 865-1111',
    website: 'https://www.denverlibrary.org/location/central-library',
  },
  {
    id: 'dpl-cherry-creek',
    systemId: 'dpl',
    systemName: 'Denver Public Library',
    name: 'Ross-Cherry Creek Branch',
    address: '305 Milwaukee St',
    city: 'Denver',
    state: 'CO',
    zip: '80206',
    lat: 39.7215,
    lon: -104.9525,
    phone: '(720) 865-0120',
    website: 'https://www.denverlibrary.org/location/ross-cherry-creek',
  },
  {
    id: 'dpl-park-hill',
    systemId: 'dpl',
    systemName: 'Denver Public Library',
    name: 'Pauline Robinson / Park Hill Branch',
    address: '4822 E Montview Blvd',
    city: 'Denver',
    state: 'CO',
    zip: '80207',
    lat: 39.7478,
    lon: -104.9315,
    phone: '(720) 865-0290',
    website: 'https://www.denverlibrary.org/location/park-hill',
  },

  // --- Boston Public Library ---
  {
    id: 'boply-central',
    systemId: 'boply',
    systemName: 'Boston Public Library',
    name: 'Central Library in Copley Square',
    address: '700 Boylston St',
    city: 'Boston',
    state: 'MA',
    zip: '02116',
    lat: 42.3495,
    lon: -71.0782,
    phone: '(617) 536-5400',
    website: 'https://www.bpl.org/locations/central/',
  },
  {
    id: 'boply-south-end',
    systemId: 'boply',
    systemName: 'Boston Public Library',
    name: 'South End Branch',
    address: '685 Tremont St',
    city: 'Boston',
    state: 'MA',
    zip: '02118',
    lat: 42.3415,
    lon: -71.0755,
    phone: '(617) 536-8241',
    website: 'https://www.bpl.org/locations/south-end/',
  },
  {
    id: 'boply-brighton',
    systemId: 'boply',
    systemName: 'Boston Public Library',
    name: 'Brighton Branch',
    address: '40 Academy Hill Rd',
    city: 'Brighton',
    state: 'MA',
    zip: '02135',
    lat: 42.3498,
    lon: -71.1555,
    phone: '(617) 782-6032',
    website: 'https://www.bpl.org/locations/brighton/',
  },

  // --- Multnomah County Library (Portland) ---
  {
    id: 'mcl-central',
    systemId: 'mcl',
    systemName: 'Multnomah County Library (Portland)',
    name: 'Central Library',
    address: '801 SW 10th Ave',
    city: 'Portland',
    state: 'OR',
    zip: '97205',
    lat: 45.5192,
    lon: -122.6825,
    phone: '(503) 988-5123',
    website: 'https://multcolib.org/location/central-library',
  },
  {
    id: 'mcl-belmont',
    systemId: 'mcl',
    systemName: 'Multnomah County Library (Portland)',
    name: 'Belmont Library',
    address: '1038 SE Cesar E Chavez Blvd',
    city: 'Portland',
    state: 'OR',
    zip: '97214',
    lat: 45.5165,
    lon: -122.6225,
    phone: '(503) 988-5123',
    website: 'https://multcolib.org/location/belmont-library',
  },

  // --- Atlanta-Fulton Public Library System ---
  {
    id: 'afpls-central',
    systemId: 'afpls',
    systemName: 'Atlanta-Fulton Public Library System',
    name: 'Central Library (Downtown Atlanta)',
    address: 'One Margaret Mitchell Sq',
    city: 'Atlanta',
    state: 'GA',
    zip: '30303',
    lat: 33.7575,
    lon: -84.3885,
    phone: '(404) 730-1700',
    website: 'https://www.fulcolibrary.org/central-library/',
  },
  {
    id: 'afpls-midtown',
    systemId: 'afpls',
    systemName: 'Atlanta-Fulton Public Library System',
    name: 'Ponce de Leon / Midtown Branch',
    address: '980 Ponce De Leon Ave NE',
    city: 'Atlanta',
    state: 'GA',
    zip: '30306',
    lat: 33.7735,
    lon: -84.3565,
    phone: '(404) 874-4861',
    website: 'https://www.fulcolibrary.org/ponce-de-leon-library/',
  },

  // --- Miami-Dade Public Library System ---
  {
    id: 'mdpls-main',
    systemId: 'mdpls',
    systemName: 'Miami-Dade Public Library System',
    name: 'Main Library (Downtown Miami)',
    address: '101 W Flagler St',
    city: 'Miami',
    state: 'FL',
    zip: '33130',
    lat: 25.7752,
    lon: -80.1962,
    phone: '(305) 375-2665',
    website: 'https://mdpls.org/branch-main',
  },
  {
    id: 'mdpls-south-beach',
    systemId: 'mdpls',
    systemName: 'Miami-Dade Public Library System',
    name: 'South Shore Branch (Miami Beach)',
    address: '131 Alton Rd',
    city: 'Miami Beach',
    state: 'FL',
    zip: '33139',
    lat: 25.7725,
    lon: -80.1365,
    phone: '(305) 535-4223',
    website: 'https://mdpls.org/branch-south-shore',
  },
];

// Merge into main exports
LIBRARY_SYSTEMS.push(...NATIONWIDE_SYSTEMS);
LIBRARY_BRANCHES.push(...NATIONWIDE_BRANCHES);
