import { LibraryBranch, LibrarySystem } from '@/types';

export const LIBRARY_SYSTEMS: LibrarySystem[] = [
  {
    id: 'spl',
    name: 'Seattle Public Library',
    city: 'Seattle',
    state: 'WA',
    website: 'https://www.spl.org',
    color: '#0284c7', // Sky Blue
    providerType: 'libcal',
  },
  {
    id: 'kcls',
    name: 'King County Library System',
    city: 'Issaquah',
    state: 'WA',
    website: 'https://kcls.org',
    color: '#059669', // Emerald
    providerType: 'libcal',
  },
  {
    id: 'nypl',
    name: 'New York Public Library',
    city: 'New York',
    state: 'NY',
    website: 'https://www.nypl.org',
    color: '#dc2626', // Red
    providerType: 'libcal',
  },
  {
    id: 'bpl',
    name: 'Brooklyn Public Library',
    city: 'Brooklyn',
    state: 'NY',
    website: 'https://www.bklynlibrary.org',
    color: '#d97706', // Amber
    providerType: 'communico',
  },
  {
    id: 'sfpl',
    name: 'San Francisco Public Library',
    city: 'San Francisco',
    state: 'CA',
    website: 'https://sfpl.org',
    color: '#7c3aed', // Purple
    providerType: 'libcal',
  },
  {
    id: 'cpl',
    name: 'Chicago Public Library',
    city: 'Chicago',
    state: 'IL',
    website: 'https://www.chipublib.org',
    color: '#2563eb', // Blue
    providerType: 'communico',
  },
  {
    id: 'apl',
    name: 'Austin Public Library',
    city: 'Austin',
    state: 'TX',
    website: 'https://library.austintexas.gov',
    color: '#ea580c', // Orange
    providerType: 'libcal',
  },
  {
    id: 'lapl',
    name: 'Los Angeles Public Library',
    city: 'Los Angeles',
    state: 'CA',
    website: 'https://www.lapl.org',
    color: '#0891b2', // Cyan
    providerType: 'libcal',
  },
  {
    id: 'boply',
    name: 'Boston Public Library',
    city: 'Boston',
    state: 'MA',
    website: 'https://www.bpl.org',
    color: '#4f46e5', // Indigo
    providerType: 'libcal',
  },
];

export const LIBRARY_BRANCHES: LibraryBranch[] = [
  // --- Seattle Public Library (SPL) ---
  {
    id: 'spl-central',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Central Library',
    address: '1000 4th Ave',
    city: 'Seattle',
    state: 'WA',
    zip: '98104',
    lat: 47.6067,
    lon: -122.3326,
    phone: '(206) 386-4636',
    website: 'https://www.spl.org/hours-and-locations/central-library',
  },
  {
    id: 'spl-ballard',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Ballard Branch',
    address: '5614 22nd Ave NW',
    city: 'Seattle',
    state: 'WA',
    zip: '98107',
    lat: 47.6698,
    lon: -122.3853,
    phone: '(206) 684-4089',
    website: 'https://www.spl.org/hours-and-locations/ballard-branch',
  },
  {
    id: 'spl-queen-anne',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Queen Anne Branch',
    address: '400 W Garfield St',
    city: 'Seattle',
    state: 'WA',
    zip: '98119',
    lat: 47.6322,
    lon: -122.3619,
    phone: '(206) 386-4227',
    website: 'https://www.spl.org/hours-and-locations/queen-anne-branch',
  },
  {
    id: 'spl-fremont',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Fremont Branch',
    address: '731 N 35th St',
    city: 'Seattle',
    state: 'WA',
    zip: '98103',
    lat: 47.6511,
    lon: -122.3486,
    phone: '(206) 684-4084',
    website: 'https://www.spl.org/hours-and-locations/fremont-branch',
  },
  {
    id: 'spl-capitol-hill',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Capitol Hill Branch',
    address: '425 Harvard Ave E',
    city: 'Seattle',
    state: 'WA',
    zip: '98102',
    lat: 47.6228,
    lon: -122.3228,
    phone: '(206) 684-4715',
    website: 'https://www.spl.org/hours-and-locations/capitol-hill-branch',
  },
  {
    id: 'spl-greenwood',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Greenwood Branch',
    address: '8016 Greenwood Ave N',
    city: 'Seattle',
    state: 'WA',
    zip: '98103',
    lat: 47.6876,
    lon: -122.3553,
    phone: '(206) 684-4086',
    website: 'https://www.spl.org/hours-and-locations/greenwood-branch',
  },
  {
    id: 'spl-west-seattle',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'West Seattle Branch',
    address: '2306 42nd Ave SW',
    city: 'Seattle',
    state: 'WA',
    zip: '98116',
    lat: 47.5828,
    lon: -122.3853,
    phone: '(206) 684-7444',
    website: 'https://www.spl.org/hours-and-locations/west-seattle-branch',
  },

  // --- King County Library System (KCLS) ---
  {
    id: 'kcls-bellevue',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Bellevue Library',
    address: '1111 110th Ave NE',
    city: 'Bellevue',
    state: 'WA',
    zip: '98004',
    lat: 47.6203,
    lon: -122.1932,
    phone: '(425) 450-1765',
    website: 'https://kcls.org/locations/1490',
  },
  {
    id: 'kcls-kirkland',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Kirkland Library',
    address: '308 Kirkland Ave',
    city: 'Kirkland',
    state: 'WA',
    zip: '98033',
    lat: 47.6766,
    lon: -122.2036,
    phone: '(425) 822-2459',
    website: 'https://kcls.org/locations/1517',
  },
  {
    id: 'kcls-redmond',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Redmond Library',
    address: '15990 NE 85th St',
    city: 'Redmond',
    state: 'WA',
    zip: '98052',
    lat: 47.6789,
    lon: -122.1265,
    phone: '(425) 885-1861',
    website: 'https://kcls.org/locations/1529',
  },
  {
    id: 'kcls-mercer-island',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Mercer Island Library',
    address: '4400 88th Ave SE',
    city: 'Mercer Island',
    state: 'WA',
    zip: '98040',
    lat: 47.5684,
    lon: -122.2215,
    phone: '(206) 236-3537',
    website: 'https://kcls.org/locations/1525',
  },

  // --- New York Public Library (NYPL) ---
  {
    id: 'nypl-schwarzman',
    systemId: 'nypl',
    systemName: 'New York Public Library',
    name: 'Stephen A. Schwarzman Building',
    address: '476 5th Ave',
    city: 'New York',
    state: 'NY',
    zip: '10018',
    lat: 40.7532,
    lon: -73.9822,
    phone: '(917) 275-6975',
    website: 'https://www.nypl.org/locations/schwarzman',
  },
  {
    id: 'nypl-snfl',
    systemId: 'nypl',
    systemName: 'New York Public Library',
    name: 'Stavros Niarchos Foundation Library (SNFL)',
    address: '455 5th Ave',
    city: 'New York',
    state: 'NY',
    zip: '10016',
    lat: 40.7518,
    lon: -73.9818,
    phone: '(212) 340-0863',
    website: 'https://www.nypl.org/locations/snfl',
  },
  {
    id: 'nypl-epiphany',
    systemId: 'nypl',
    systemName: 'New York Public Library',
    name: 'Epiphany Library',
    address: '228 E 23rd St',
    city: 'New York',
    state: 'NY',
    zip: '10010',
    lat: 40.7381,
    lon: -73.9809,
    phone: '(212) 679-2645',
    website: 'https://www.nypl.org/locations/epiphany',
  },
  {
    id: 'nypl-53rd',
    systemId: 'nypl',
    systemName: 'New York Public Library',
    name: '53rd Street Library',
    address: '18 W 53rd St',
    city: 'New York',
    state: 'NY',
    zip: '10019',
    lat: 40.7612,
    lon: -73.9772,
    phone: '(212) 714-8400',
    website: 'https://www.nypl.org/locations/53rd-street',
  },

  // --- Brooklyn Public Library (BPL) ---
  {
    id: 'bpl-central',
    systemId: 'bpl',
    systemName: 'Brooklyn Public Library',
    name: 'Central Library',
    address: '10 Grand Army Plaza',
    city: 'Brooklyn',
    state: 'NY',
    zip: '11238',
    lat: 40.6725,
    lon: -73.9682,
    phone: '(718) 230-2100',
    website: 'https://www.bklynlibrary.org/locations/central',
  },
  {
    id: 'bpl-park-slope',
    systemId: 'bpl',
    systemName: 'Brooklyn Public Library',
    name: 'Park Slope Library',
    address: '431 6th Ave',
    city: 'Brooklyn',
    state: 'NY',
    zip: '11215',
    lat: 40.6695,
    lon: -73.9841,
    phone: '(718) 832-1853',
    website: 'https://www.bklynlibrary.org/locations/park-slope',
  },
  {
    id: 'bpl-heights',
    systemId: 'bpl',
    systemName: 'Brooklyn Public Library',
    name: 'Brooklyn Heights Library',
    address: '286 Cadman Plaza W',
    city: 'Brooklyn',
    state: 'NY',
    zip: '11201',
    lat: 40.6958,
    lon: -73.9915,
    phone: '(718) 623-7100',
    website: 'https://www.bklynlibrary.org/locations/brooklyn-heights',
  },

  // --- San Francisco Public Library (SFPL) ---
  {
    id: 'sfpl-main',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Main Library',
    address: '100 Larkin St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94102',
    lat: 37.7788,
    lon: -122.4168,
    phone: '(415) 557-4400',
    website: 'https://sfpl.org/locations/main-library',
  },
  {
    id: 'sfpl-mission',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Mission Branch',
    address: '300 Bartlett St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94110',
    lat: 37.7525,
    lon: -122.4198,
    phone: '(415) 355-2800',
    website: 'https://sfpl.org/locations/mission',
  },
  {
    id: 'sfpl-richmond',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Richmond / Senator Milton Marks Branch',
    address: '351 9th Ave',
    city: 'San Francisco',
    state: 'CA',
    zip: '94118',
    lat: 37.7815,
    lon: -122.4678,
    phone: '(415) 355-5600',
    website: 'https://sfpl.org/locations/richmond',
  },
  {
    id: 'sfpl-marina',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Marina Branch',
    address: '1890 Chestnut St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94123',
    lat: 37.8005,
    lon: -122.4352,
    phone: '(415) 355-2823',
    website: 'https://sfpl.org/locations/marina',
  },

  // --- Chicago Public Library (CPL) ---
  {
    id: 'cpl-harold',
    systemId: 'cpl',
    systemName: 'Chicago Public Library',
    name: 'Harold Washington Library Center',
    address: '400 S State St',
    city: 'Chicago',
    state: 'IL',
    zip: '60605',
    lat: 41.8763,
    lon: -87.6281,
    phone: '(312) 747-4300',
    website: 'https://www.chipublib.org/locations/34/',
  },
  {
    id: 'cpl-lincoln-park',
    systemId: 'cpl',
    systemName: 'Chicago Public Library',
    name: 'Lincoln Park Branch',
    address: '1150 W Fullerton Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60614',
    lat: 41.9252,
    lon: -87.6582,
    phone: '(312) 744-1926',
    website: 'https://www.chipublib.org/locations/44/',
  },
  {
    id: 'cpl-bucktown',
    systemId: 'cpl',
    systemName: 'Chicago Public Library',
    name: 'Bucktown-Wicker Park Branch',
    address: '1701 N Milwaukee Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60647',
    lat: 41.9126,
    lon: -87.6823,
    phone: '(312) 744-6022',
    website: 'https://www.chipublib.org/locations/15/',
  },

  // --- Austin Public Library (APL) ---
  {
    id: 'apl-central',
    systemId: 'apl',
    systemName: 'Austin Public Library',
    name: 'Central Library',
    address: '710 W Cesar Chavez St',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    lat: 30.2662,
    lon: -97.7495,
    phone: '(512) 974-7400',
    website: 'https://library.austintexas.gov/central-library',
  },
  {
    id: 'apl-twin-oaks',
    systemId: 'apl',
    systemName: 'Austin Public Library',
    name: 'Twin Oaks Branch',
    address: '1800 S 5th St',
    city: 'Austin',
    state: 'TX',
    zip: '78704',
    lat: 30.2458,
    lon: -97.7592,
    phone: '(512) 974-9980',
    website: 'https://library.austintexas.gov/twin-oaks-branch',
  },

  // --- Los Angeles Public Library (LAPL) ---
  {
    id: 'lapl-central',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Central Library',
    address: '630 W 5th St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90071',
    lat: 34.0503,
    lon: -118.2553,
    phone: '(213) 228-7000',
    website: 'https://www.lapl.org/branches/central-library',
  },
  {
    id: 'lapl-venice',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Venice - Abbot Kinney Memorial Branch',
    address: '501 S Venice Blvd',
    city: 'Venice',
    state: 'CA',
    zip: '90291',
    lat: 33.9877,
    lon: -118.4632,
    phone: '(310) 821-1769',
    website: 'https://www.lapl.org/branches/venice',
  },
];
