import { LibraryBranch, LibrarySystem } from '@/types';

export const LIBRARY_SYSTEMS: LibrarySystem[] = [
  {
    id: 'ppl',
    name: 'Pasadena Public Library',
    city: 'Pasadena',
    state: 'CA',
    website: 'https://www.cityofpasadena.net/library/',
    color: '#e11d48', // Rose
    providerType: 'libcal',
  },
  {
    id: 'sppl',
    name: 'South Pasadena Public Library',
    city: 'South Pasadena',
    state: 'CA',
    website: 'https://www.southpasadenaca.gov/government/departments/library',
    color: '#0d9488', // Teal
    providerType: 'libcal',
  },
  {
    id: 'ald',
    name: 'Altadena Library District',
    city: 'Altadena',
    state: 'CA',
    website: 'https://www.altadenalibrary.net',
    color: '#d97706', // Amber
    providerType: 'libcal',
  },
  {
    id: 'glac',
    name: 'Glendale Library, Arts & Culture',
    city: 'Glendale',
    state: 'CA',
    website: 'https://www.glendaleca.gov/government/departments/library-arts-culture',
    color: '#7c3aed', // Purple
    providerType: 'libcal',
  },
  {
    id: 'crowell',
    name: 'Crowell Public Library (San Marino)',
    city: 'San Marino',
    state: 'CA',
    website: 'https://www.crowellpubliclibrary.org',
    color: '#059669', // Emerald
    providerType: 'libcal',
  },
  {
    id: 'alhambra',
    name: 'Alhambra Civic Center Library',
    city: 'Alhambra',
    state: 'CA',
    website: 'https://www.alhambralibrary.org',
    color: '#2563eb', // Blue
    providerType: 'communico',
  },
  {
    id: 'lacounty',
    name: 'LA County Library',
    city: 'Los Angeles',
    state: 'CA',
    website: 'https://lacountylibrary.org',
    color: '#ea580c', // Orange
    providerType: 'libcal',
  },
  {
    id: 'lapl',
    name: 'Los Angeles Public Library',
    city: 'Los Angeles',
    state: 'CA',
    website: 'https://www.lapl.org',
    color: '#0891b2', // Cyan
    providerType: 'libcal',
  },
  {
    id: 'spl',
    name: 'Seattle Public Library',
    city: 'Seattle',
    state: 'WA',
    website: 'https://www.spl.org',
    color: '#0284c7', // Sky Blue
    providerType: 'libcal',
  },
  {
    id: 'kcls',
    name: 'King County Library System',
    city: 'Issaquah',
    state: 'WA',
    website: 'https://kcls.org',
    color: '#059669',
    providerType: 'libcal',
  },
  {
    id: 'nypl',
    name: 'New York Public Library',
    city: 'New York',
    state: 'NY',
    website: 'https://www.nypl.org',
    color: '#dc2626',
    providerType: 'libcal',
  },
  {
    id: 'bpl',
    name: 'Brooklyn Public Library',
    city: 'Brooklyn',
    state: 'NY',
    website: 'https://www.bklynlibrary.org',
    color: '#d97706',
    providerType: 'communico',
  },
  {
    id: 'sfpl',
    name: 'San Francisco Public Library',
    city: 'San Francisco',
    state: 'CA',
    website: 'https://sfpl.org',
    color: '#7c3aed',
    providerType: 'libcal',
  },
  {
    id: 'cpl',
    name: 'Chicago Public Library',
    city: 'Chicago',
    state: 'IL',
    website: 'https://www.chipublib.org',
    color: '#2563eb',
    providerType: 'communico',
  },
  {
    id: 'apl',
    name: 'Austin Public Library',
    city: 'Austin',
    state: 'TX',
    website: 'https://library.austintexas.gov',
    color: '#ea580c',
    providerType: 'libcal',
  },
];

export const LIBRARY_BRANCHES: LibraryBranch[] = [
  // ==========================================
  // PASADENA PUBLIC LIBRARY (PPL)
  // ==========================================
  {
    id: 'ppl-jefferson',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: "Jefferson Branch (Children's & Youth)",
    address: '1500 E Villa St',
    city: 'Pasadena',
    state: 'CA',
    zip: '91106',
    lat: 34.1504,
    lon: -118.1205,
    phone: '(626) 744-8046',
    website: 'https://www.cityofpasadena.net/library/branches/jefferson-branch-library/',
  },
  {
    id: 'ppl-hastings',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'Hastings Branch',
    address: '3325 E Orange Grove Blvd',
    city: 'Pasadena',
    state: 'CA',
    zip: '91107',
    lat: 34.1673,
    lon: -118.0837,
    phone: '(626) 744-7262',
    website: 'https://www.cityofpasadena.net/library/branches/hastings-branch-library/',
  },
  {
    id: 'ppl-allendale',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'Allendale Branch',
    address: '1130 S Marengo Ave',
    city: 'Pasadena',
    state: 'CA',
    zip: '91106',
    lat: 34.1299,
    lon: -118.1507,
    phone: '(626) 744-7260',
    website: 'https://www.cityofpasadena.net/library/branches/allendale-branch-library/',
  },
  {
    id: 'ppl-hill-ave',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'Hill Avenue Branch',
    address: '55 S Hill Ave',
    city: 'Pasadena',
    state: 'CA',
    zip: '91106',
    lat: 34.1456,
    lon: -118.1258,
    phone: '(626) 744-7264',
    website: 'https://www.cityofpasadena.net/library/branches/hill-avenue-branch-library/',
  },
  {
    id: 'ppl-lamanda-park',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'Lamanda Park Branch',
    address: '140 S Altadena Dr',
    city: 'Pasadena',
    state: 'CA',
    zip: '91107',
    lat: 34.1451,
    lon: -118.0934,
    phone: '(626) 744-7266',
    website: 'https://www.cityofpasadena.net/library/branches/lamanda-park-branch-library/',
  },
  {
    id: 'ppl-la-pintoresca',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'La Pintoresca Branch',
    address: '1355 N Raymond Ave',
    city: 'Pasadena',
    state: 'CA',
    zip: '91103',
    lat: 34.1675,
    lon: -118.1498,
    phone: '(626) 744-7268',
    website: 'https://www.cityofpasadena.net/library/branches/la-pintoresca-branch-library/',
  },
  {
    id: 'ppl-santa-catalina',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'Santa Catalina Branch',
    address: '999 E Washington Blvd',
    city: 'Pasadena',
    state: 'CA',
    zip: '91104',
    lat: 34.1624,
    lon: -118.1318,
    phone: '(626) 744-7272',
    website: 'https://www.cityofpasadena.net/library/branches/santa-catalina-branch-library/',
  },
  {
    id: 'ppl-san-rafael',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'San Rafael Branch',
    address: '1240 Nithsdale Rd',
    city: 'Pasadena',
    state: 'CA',
    zip: '91105',
    lat: 34.1408,
    lon: -118.1793,
    phone: '(626) 744-7270',
    website: 'https://www.cityofpasadena.net/library/branches/san-rafael-branch-library/',
  },
  {
    id: 'ppl-linda-vista',
    systemId: 'ppl',
    systemName: 'Pasadena Public Library',
    name: 'Linda Vista Branch',
    address: '1281 Bryant St',
    city: 'Pasadena',
    state: 'CA',
    zip: '91103',
    lat: 34.1601,
    lon: -118.1742,
    phone: '(626) 744-7278',
    website: 'https://www.cityofpasadena.net/library/branches/linda-vista-branch-library/',
  },

  // ==========================================
  // SOUTH PASADENA PUBLIC LIBRARY
  // ==========================================
  {
    id: 'sppl-main',
    systemId: 'sppl',
    systemName: 'South Pasadena Public Library',
    name: 'South Pasadena Public Library',
    address: '1100 Oxley St',
    city: 'South Pasadena',
    state: 'CA',
    zip: '91030',
    lat: 34.1166,
    lon: -118.1528,
    phone: '(626) 403-7330',
    website: 'https://www.southpasadenaca.gov/government/departments/library',
  },

  // ==========================================
  // ALTADENA LIBRARY DISTRICT (ALD)
  // ==========================================
  {
    id: 'ald-main',
    systemId: 'ald',
    systemName: 'Altadena Library District',
    name: 'Altadena Main Library',
    address: '600 E Mariposa St',
    city: 'Altadena',
    state: 'CA',
    zip: '91001',
    lat: 34.1925,
    lon: -118.1388,
    phone: '(626) 798-0833',
    website: 'https://www.altadenalibrary.net',
  },
  {
    id: 'ald-bob-lucas',
    systemId: 'ald',
    systemName: 'Altadena Library District',
    name: 'Bob Lucas Memorial Branch',
    address: '2659 Lincoln Ave',
    city: 'Altadena',
    state: 'CA',
    zip: '91001',
    lat: 34.1843,
    lon: -118.1593,
    phone: '(626) 798-8338',
    website: 'https://www.altadenalibrary.net/locations/bob-lucas/',
  },

  // ==========================================
  // CROWELL PUBLIC LIBRARY (SAN MARINO)
  // ==========================================
  {
    id: 'crowell-main',
    systemId: 'crowell',
    systemName: 'Crowell Public Library',
    name: 'Crowell Public Library',
    address: '1890 Huntington Dr',
    city: 'San Marino',
    state: 'CA',
    zip: '91108',
    lat: 34.1221,
    lon: -118.1189,
    phone: '(626) 300-0777',
    website: 'https://www.crowellpubliclibrary.org',
  },

  // ==========================================
  // ALHAMBRA CIVIC CENTER LIBRARY
  // ==========================================
  {
    id: 'alhambra-main',
    systemId: 'alhambra',
    systemName: 'Alhambra Civic Center Library',
    name: 'Alhambra Civic Center Library',
    address: '100 W Main St',
    city: 'Alhambra',
    state: 'CA',
    zip: '91801',
    lat: 34.0955,
    lon: -118.1287,
    phone: '(626) 570-5008',
    website: 'https://www.alhambralibrary.org',
  },

  // ==========================================
  // GLENDALE LIBRARY, ARTS & CULTURE
  // ==========================================
  {
    id: 'glac-central',
    systemId: 'glac',
    systemName: 'Glendale Library, Arts & Culture',
    name: 'Glendale Central Library',
    address: '222 E Harvard St',
    city: 'Glendale',
    state: 'CA',
    zip: '91205',
    lat: 34.1438,
    lon: -118.2525,
    phone: '(818) 548-2021',
    website: 'https://www.glendaleca.gov/government/departments/library-arts-culture/central-library',
  },
  {
    id: 'glac-brand',
    systemId: 'glac',
    systemName: 'Glendale Library, Arts & Culture',
    name: 'Brand Library & Art Center',
    address: '1601 W Mountain St',
    city: 'Glendale',
    state: 'CA',
    zip: '91201',
    lat: 34.1818,
    lon: -118.2713,
    phone: '(818) 548-2051',
    website: 'https://www.glendaleca.gov/government/departments/library-arts-culture/brand-library-art-center',
  },
  {
    id: 'glac-adams-square',
    systemId: 'glac',
    systemName: 'Glendale Library, Arts & Culture',
    name: 'Adams Square Branch Library',
    address: '1100 E Chevy Chase Dr',
    city: 'Glendale',
    state: 'CA',
    zip: '91205',
    lat: 34.1378,
    lon: -118.2372,
    phone: '(818) 548-3830',
    website: 'https://www.glendaleca.gov/government/departments/library-arts-culture',
  },
  {
    id: 'glac-montrose',
    systemId: 'glac',
    systemName: 'Glendale Library, Arts & Culture',
    name: 'Montrose Branch Library',
    address: '2465 Honolulu Ave',
    city: 'Montrose',
    state: 'CA',
    zip: '91020',
    lat: 34.2081,
    lon: -118.2307,
    phone: '(818) 548-2048',
    website: 'https://www.glendaleca.gov/government/departments/library-arts-culture',
  },

  // ==========================================
  // LA COUNTY LIBRARY (SAN GABRIEL VALLEY / FOOTHILL)
  // ==========================================
  {
    id: 'lacounty-san-gabriel',
    systemId: 'lacounty',
    systemName: 'LA County Library',
    name: 'San Gabriel Library',
    address: '500 S Del Mar Ave',
    city: 'San Gabriel',
    state: 'CA',
    zip: '91776',
    lat: 34.0945,
    lon: -118.1005,
    phone: '(626) 287-0761',
    website: 'https://lacountylibrary.org/san-gabriel-library/',
  },
  {
    id: 'lacounty-temple-city',
    systemId: 'lacounty',
    systemName: 'LA County Library',
    name: 'Temple City Library',
    address: '5939 Golden West Ave',
    city: 'Temple City',
    state: 'CA',
    zip: '91780',
    lat: 34.1085,
    lon: -118.0583,
    phone: '(626) 285-2136',
    website: 'https://lacountylibrary.org/temple-city-library/',
  },
  {
    id: 'lacounty-rosemead',
    systemId: 'lacounty',
    systemName: 'LA County Library',
    name: 'Rosemead Library',
    address: '8800 Valley Blvd',
    city: 'Rosemead',
    state: 'CA',
    zip: '91770',
    lat: 34.0709,
    lon: -118.0833,
    phone: '(626) 572-2320',
    website: 'https://lacountylibrary.org/rosemead-library/',
  },
  {
    id: 'lacounty-la-canada',
    systemId: 'lacounty',
    systemName: 'LA County Library',
    name: 'La Cañada Flintridge Library',
    address: '4545 N Oakwood Ave',
    city: 'La Cañada Flintridge',
    state: 'CA',
    zip: '91011',
    lat: 34.2045,
    lon: -118.2014,
    phone: '(818) 790-0522',
    website: 'https://lacountylibrary.org/la-canada-flintridge-library/',
  },

  // ==========================================
  // LOS ANGELES PUBLIC LIBRARY (LAPL) - Close to Pasadena + Central
  // ==========================================
  {
    id: 'lapl-eagle-rock',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Eagle Rock Branch',
    address: '2225 Colorado Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90041',
    lat: 34.1396,
    lon: -118.2114,
    phone: '(323) 258-8078',
    website: 'https://www.lapl.org/branches/eagle-rock',
  },
  {
    id: 'lapl-arroyo-seco',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Arroyo Seco Regional Branch',
    address: '6145 N Figueroa St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90042',
    lat: 34.1105,
    lon: -118.1923,
    phone: '(323) 256-3141',
    website: 'https://www.lapl.org/branches/arroyo-seco',
  },
  {
    id: 'lapl-chinatown',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Chinatown Branch',
    address: '639 N Hill St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90012',
    lat: 34.0622,
    lon: -118.2385,
    phone: '(213) 620-0925',
    website: 'https://www.lapl.org/branches/chinatown',
  },
  {
    id: 'lapl-lincoln-heights',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Lincoln Heights Branch',
    address: '2530 Workman St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90031',
    lat: 34.0735,
    lon: -118.2155,
    phone: '(323) 225-9201',
    website: 'https://www.lapl.org/branches/lincoln-heights',
  },
  {
    id: 'lapl-central',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Central Library',
    address: '630 W 5th St',
    city: 'Los Angeles',
    state: 'CA',
    zip: '90071',
    lat: 34.0503,
    lon: -118.2553,
    phone: '(213) 228-7000',
    website: 'https://www.lapl.org/branches/central-library',
  },
  {
    id: 'lapl-venice',
    systemId: 'lapl',
    systemName: 'Los Angeles Public Library',
    name: 'Venice - Abbot Kinney Memorial Branch',
    address: '501 S Venice Blvd',
    city: 'Venice',
    state: 'CA',
    zip: '90291',
    lat: 33.9877,
    lon: -118.4632,
    phone: '(310) 821-1769',
    website: 'https://www.lapl.org/branches/venice',
  },

  // ==========================================
  // SEATTLE PUBLIC LIBRARY (SPL)
  // ==========================================
  {
    id: 'spl-central',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Central Library',
    address: '1000 4th Ave',
    city: 'Seattle',
    state: 'WA',
    zip: '98104',
    lat: 47.6067,
    lon: -122.3326,
    phone: '(206) 386-4636',
    website: 'https://www.spl.org/hours-and-locations/central-library',
  },
  {
    id: 'spl-ballard',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Ballard Branch',
    address: '5614 22nd Ave NW',
    city: 'Seattle',
    state: 'WA',
    zip: '98107',
    lat: 47.6698,
    lon: -122.3853,
    phone: '(206) 684-4089',
    website: 'https://www.spl.org/hours-and-locations/ballard-branch',
  },
  {
    id: 'spl-queen-anne',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Queen Anne Branch',
    address: '400 W Garfield St',
    city: 'Seattle',
    state: 'WA',
    zip: '98119',
    lat: 47.6322,
    lon: -122.3619,
    phone: '(206) 386-4227',
    website: 'https://www.spl.org/hours-and-locations/queen-anne-branch',
  },
  {
    id: 'spl-fremont',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Fremont Branch',
    address: '731 N 35th St',
    city: 'Seattle',
    state: 'WA',
    zip: '98103',
    lat: 47.6511,
    lon: -122.3486,
    phone: '(206) 684-4084',
    website: 'https://www.spl.org/hours-and-locations/fremont-branch',
  },
  {
    id: 'spl-capitol-hill',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Capitol Hill Branch',
    address: '425 Harvard Ave E',
    city: 'Seattle',
    state: 'WA',
    zip: '98102',
    lat: 47.6228,
    lon: -122.3228,
    phone: '(206) 684-4715',
    website: 'https://www.spl.org/hours-and-locations/capitol-hill-branch',
  },
  {
    id: 'spl-greenwood',
    systemId: 'spl',
    systemName: 'Seattle Public Library',
    name: 'Greenwood Branch',
    address: '8016 Greenwood Ave N',
    city: 'Seattle',
    state: 'WA',
    zip: '98103',
    lat: 47.6876,
    lon: -122.3553,
    phone: '(206) 684-4086',
    website: 'https://www.spl.org/hours-and-locations/greenwood-branch',
  },

  // ==========================================
  // KING COUNTY LIBRARY SYSTEM (KCLS)
  // ==========================================
  {
    id: 'kcls-bellevue',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Bellevue Library',
    address: '1111 110th Ave NE',
    city: 'Bellevue',
    state: 'WA',
    zip: '98004',
    lat: 47.6203,
    lon: -122.1932,
    phone: '(425) 450-1765',
    website: 'https://kcls.org/locations/1490',
  },
  {
    id: 'kcls-kirkland',
    systemId: 'kcls',
    systemName: 'King County Library System',
    name: 'Kirkland Library',
    address: '308 Kirkland Ave',
    city: 'Kirkland',
    state: 'WA',
    zip: '98033',
    lat: 47.6766,
    lon: -122.2036,
    phone: '(425) 822-2459',
    website: 'https://kcls.org/locations/1517',
  },

  // ==========================================
  // NEW YORK PUBLIC LIBRARY & BROOKLYN
  // ==========================================
  {
    id: 'nypl-schwarzman',
    systemId: 'nypl',
    systemName: 'New York Public Library',
    name: 'Stephen A. Schwarzman Building',
    address: '476 5th Ave',
    city: 'New York',
    state: 'NY',
    zip: '10018',
    lat: 40.7532,
    lon: -73.9822,
    phone: '(917) 275-6975',
    website: 'https://www.nypl.org/locations/schwarzman',
  },
  {
    id: 'nypl-snfl',
    systemId: 'nypl',
    systemName: 'New York Public Library',
    name: 'Stavros Niarchos Foundation Library (SNFL)',
    address: '455 5th Ave',
    city: 'New York',
    state: 'NY',
    zip: '10016',
    lat: 40.7518,
    lon: -73.9818,
    phone: '(212) 340-0863',
    website: 'https://www.nypl.org/locations/snfl',
  },
  {
    id: 'bpl-central',
    systemId: 'bpl',
    systemName: 'Brooklyn Public Library',
    name: 'Central Library',
    address: '10 Grand Army Plaza',
    city: 'Brooklyn',
    state: 'NY',
    zip: '11238',
    lat: 40.6725,
    lon: -73.9682,
    phone: '(718) 230-2100',
    website: 'https://www.bklynlibrary.org/locations/central',
  },
  {
    id: 'bpl-park-slope',
    systemId: 'bpl',
    systemName: 'Brooklyn Public Library',
    name: 'Park Slope Library',
    address: '431 6th Ave',
    city: 'Brooklyn',
    state: 'NY',
    zip: '11215',
    lat: 40.6695,
    lon: -73.9841,
    phone: '(718) 832-1853',
    website: 'https://www.bklynlibrary.org/locations/park-slope',
  },

  // ==========================================
  // SAN FRANCISCO PUBLIC LIBRARY (SFPL)
  // ==========================================
  {
    id: 'sfpl-main',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Main Library (Civic Center)',
    address: '100 Larkin St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94102',
    lat: 37.7788,
    lon: -122.4168,
    phone: '(415) 557-4400',
    website: 'https://sfpl.org/locations/main-library',
  },
  {
    id: 'sfpl-mission',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Mission Branch',
    address: '300 Bartlett St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94110',
    lat: 37.7525,
    lon: -122.4198,
    phone: '(415) 355-2800',
    website: 'https://sfpl.org/locations/mission',
  },
  {
    id: 'sfpl-richmond',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Richmond Branch',
    address: '351 9th Ave',
    city: 'San Francisco',
    state: 'CA',
    zip: '94118',
    lat: 37.7815,
    lon: -122.4678,
    phone: '(415) 355-5600',
    website: 'https://sfpl.org/locations/richmond',
  },
  {
    id: 'sfpl-sunset',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Sunset Branch',
    address: '1370 18th Ave',
    city: 'San Francisco',
    state: 'CA',
    zip: '94122',
    lat: 37.7618,
    lon: -122.4764,
    phone: '(415) 355-2818',
    website: 'https://sfpl.org/locations/sunset',
  },
  {
    id: 'sfpl-marina',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Marina Branch',
    address: '1890 Chestnut St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94123',
    lat: 37.8005,
    lon: -122.4352,
    phone: '(415) 355-2823',
    website: 'https://sfpl.org/locations/marina',
  },
  {
    id: 'sfpl-north-beach',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'North Beach Branch',
    address: '850 Columbus Ave',
    city: 'San Francisco',
    state: 'CA',
    zip: '94133',
    lat: 37.8016,
    lon: -122.4132,
    phone: '(415) 355-5626',
    website: 'https://sfpl.org/locations/north-beach',
  },
  {
    id: 'sfpl-chinatown',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Chinatown / Him Mark Lai Branch',
    address: '1135 Powell St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94108',
    lat: 37.7947,
    lon: -122.4093,
    phone: '(415) 355-2888',
    website: 'https://sfpl.org/locations/chinatown',
  },
  {
    id: 'sfpl-noe-valley',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Noe Valley / Sally Brunn Branch',
    address: '451 Jersey St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94114',
    lat: 37.7513,
    lon: -122.4347,
    phone: '(415) 355-5707',
    website: 'https://sfpl.org/locations/noe-valley',
  },
  {
    id: 'sfpl-bernal-heights',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Bernal Heights Branch',
    address: '500 Cortland Ave',
    city: 'San Francisco',
    state: 'CA',
    zip: '94110',
    lat: 37.7391,
    lon: -122.4158,
    phone: '(415) 355-2810',
    website: 'https://sfpl.org/locations/bernal-heights',
  },
  {
    id: 'sfpl-glen-park',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Glen Park Branch',
    address: '2825 Diamond St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94131',
    lat: 37.7335,
    lon: -122.4338,
    phone: '(415) 355-2858',
    website: 'https://sfpl.org/locations/glen-park',
  },
  {
    id: 'sfpl-eureka-valley',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Eureka Valley / Harvey Milk Memorial Branch',
    address: '1 José Sarria Ct',
    city: 'San Francisco',
    state: 'CA',
    zip: '94114',
    lat: 37.7612,
    lon: -122.4348,
    phone: '(415) 355-5616',
    website: 'https://sfpl.org/locations/eureka-valley',
  },
  {
    id: 'sfpl-west-portal',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'West Portal Branch',
    address: '190 Lenox Way',
    city: 'San Francisco',
    state: 'CA',
    zip: '94127',
    lat: 37.7402,
    lon: -122.4665,
    phone: '(415) 355-2886',
    website: 'https://sfpl.org/locations/west-portal',
  },
  {
    id: 'sfpl-parkside',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Parkside Branch',
    address: '1200 Taraval St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94116',
    lat: 37.7431,
    lon: -122.4789,
    phone: '(415) 355-5770',
    website: 'https://sfpl.org/locations/parkside',
  },
  {
    id: 'sfpl-western-addition',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Western Addition Branch',
    address: '1550 Scott St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94115',
    lat: 37.7842,
    lon: -122.4382,
    phone: '(415) 355-5727',
    website: 'https://sfpl.org/locations/western-addition',
  },
  {
    id: 'sfpl-presidio',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Presidio Branch',
    address: '3150 Sacramento St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94115',
    lat: 37.7885,
    lon: -122.4452,
    phone: '(415) 355-5660',
    website: 'https://sfpl.org/locations/presidio',
  },
  {
    id: 'sfpl-potrero',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Potrero Branch',
    address: '1616 20th St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94107',
    lat: 37.7618,
    lon: -122.3985,
    phone: '(415) 355-2822',
    website: 'https://sfpl.org/locations/potrero',
  },
  {
    id: 'sfpl-mission-bay',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Mission Bay Branch',
    address: '960 4th St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94158',
    lat: 37.7735,
    lon: -122.3932,
    phone: '(415) 355-2838',
    website: 'https://sfpl.org/locations/mission-bay',
  },
  {
    id: 'sfpl-bayview',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Bayview / Linda Brooks-Burton Branch',
    address: '5075 3rd St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94124',
    lat: 37.7303,
    lon: -122.3892,
    phone: '(415) 355-5757',
    website: 'https://sfpl.org/locations/bayview',
  },
  {
    id: 'sfpl-park',
    systemId: 'sfpl',
    systemName: 'San Francisco Public Library',
    name: 'Park Branch (Haight-Ashbury)',
    address: '1833 Page St',
    city: 'San Francisco',
    state: 'CA',
    zip: '94117',
    lat: 37.7705,
    lon: -122.4498,
    phone: '(415) 355-5656',
    website: 'https://sfpl.org/locations/park',
  },

  // ==========================================
  // CHICAGO & AUSTIN
  // ==========================================
  {
    id: 'cpl-lincoln-park',
    systemId: 'cpl',
    systemName: 'Chicago Public Library',
    name: 'Lincoln Park Branch',
    address: '1150 W Fullerton Ave',
    city: 'Chicago',
    state: 'IL',
    zip: '60614',
    lat: 41.9252,
    lon: -87.6582,
    phone: '(312) 744-1926',
    website: 'https://www.chipublib.org/locations/44/',
  },
  {
    id: 'apl-central',
    systemId: 'apl',
    systemName: 'Austin Public Library',
    name: 'Central Library',
    address: '710 W Cesar Chavez St',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    lat: 30.2662,
    lon: -97.7495,
    phone: '(512) 974-7400',
    website: 'https://library.austintexas.gov/central-library',
  },
];
